services:
  - type: web
    name: langchain-qa-app
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.app:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: GROQ_API_KEY
        fromDatabase: true
